name: phpstan

on:
  pull_request:
#    paths:
#      - 'src/**'
#      - 'tests/**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.1", "8.2" ]
    steps:
      - uses: actions/checkout@v3

      - name: Dockerfileからイメージをビルド
        run: docker build --build_arg= PHP_VERSION=${{ matrix.php }} -t phpstan ./docker

      - name: Composer install
        run: docker run --rm -v ${{ github.workspace }}:/var/www/html phpstan composer install

      - name: PHPStan実行
        run: docker run --rm -v ${{ github.workspace }}:/var/www/html phpstan vendor/bin/phpstan analyse --memory-limit=512M


